### ISSUE TITLE
can't open this website? https://github.com/csiro-robotics/Uncertainty-LPR?

### ISSUE THREAD

**Issue by wpumain** [csiro-robotics/Forest_Localisation#1]
I have read your paper [Uncertainty-Aware Lidar Place Recognition in Novel Environments]  recently and have benefited a lot. Thank you for sharing an excellent paper.
  But  I  can't open this website?
https://github.com/csiro-robotics/Uncertainty-LPR
Can you share the code in your paper [Uncertainty-Aware Lidar Place Recognition in Novel Environments] ?
Think you.

**Comment by mramezani64** [comment]
This link is for another paper which is under review. Once the paper is accepted, we will release the code.
